exclude: "alpine\\.js$"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/biomejs/pre-commit
  rev: 221fa73eac76e0540995318b44e2efb2774af990  # frozen: v2.5.14
  hooks:
  - id: biome-check
    additional_dependencies:
    - '@biomejs/biome@2.3.8'
    language_version: default

- repo: https://github.com/adamchainz/django-upgrade
  rev: e668ea858b908d23a9702b24214f4fc5d07ed50f  # frozen: 1.32.0
  hooks:
  - id: django-upgrade
    args: [--target-version, "3.2"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: a56c0b927e6465d37cae3e97d35d4d18ab2b96cd  # frozen: v0.16.9
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    additional_dependencies:
    - mypy>=1.10
    - django-stubs[compatible-mypy]>=5
    - django>=3.2
    - pytest-django>=4.8
    types: [python]
    files: ^(src|example)/
    pass_filenames: false
    args: [src/django_form_alpine, example]

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 59e7b26529dc6f15c43063064b8b06ded60d0910  # frozen: v2.29.4
  hooks:
  - id: pyproject-fmt
