[tox]
env_list =
    py39-dj32
    py310-dj32
    py39-dj40
    py310-dj40
    py39-dj41
    py311-dj41
    py39-dj42
    py312-dj42
    py310-dj50
    py312-dj50
    py310-dj51
    py313-dj51
    py310-dj52
    py314-dj52

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest
    pytest-django
    pytest-cov
    dj32: django>=3.2,<3.3
    dj40: django>=4.0,<4.1
    dj41: django>=4.1,<4.2
    dj42: django>=4.2,<4.3
    dj50: django>=5.0,<5.1
    dj51: django>=5.1,<5.2
    dj52: django>=5.2,<5.3
commands =
    pytest tests --ignore=tests/e2e {posargs}
